config/routes.rb
Rails.application.routes.draw do
  get 'books/available'
  get 'books/reserved'
  get 'books/bought'

  root to: "books#available"
  get 'get_book/:book_id/:option', to: 'books#get_book', as: 'get_book_info'
  post 'reserve/:book_id', to: 'books#reserve_book', as: 'reserve_book'
  post 'unreserve/:book_id', to: 'books#unreserve_book', as: 'unreserve_book'

  post 'pay', to: 'books#pay_book', as: 'pay_book'
  delete 'delete/:book', to: 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def available
    @books = Book.where(status: 0)
  end

  def reserved
    @books = Book.where(status: 1)
  end

  def bought
    @books = Book.where(status: 2)
  end

  def get_book
    @book = Book.find(params[:book_id])
    @type = params[:option]
  end

  def reserve_book
    sleep 5
    @book = Book.find(params[:book_id])
    @book.status = 1
    @book.save
    @books = Book.where(status: 0)

  end

  def unreserve_book
    @book = Book.find(params[:book_id])
    @book.status = 0
    @book.save
    @books = Book.where(status: 1)

  end
  
  def pay_book
    @book = Book.find(params[:book][:book_id].to_i)
    
    if (Time.now.utc - @book.updated_at.utc).to_i > 15 #Evaluar el tiempo que paso desde que se agrego a reservado
      @book.status = 0 
    else
      @book.status = 2
    end
    @book.save
    @books = Book.where(status: 1)
  end

  def destroy
    @book = Book.find(params[:book])
    @book.destroy
    @books = Book.where(status: 2)
  end
  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="col-4 my-3">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <h6 class="card-subtitle mb-2 text-muted"> <b>Author: </b> <%=book.author %></h6>
            <p class="card-text"><%= truncate(book.review, :length => 200) %></p>
            <%= link_to 'Details', get_book_info_path(book, 'ver'), remote: true, class: "btn btn-primary" %>
            <% if book.status == 0 %>
                <%= link_to 'Reserved', get_book_info_path(book, 'reservar'), remote: true, class: "btn btn-outline-info" %>
            <% elsif book.status == 1 %>
                <%= link_to 'Bought',  root_path, class: "btn btn-primary", data: { toggle: 'modal', target: '#payBookModal'}, class: "btn btn-outline-success" %>
                <%= link_to '<img src="https://cdn1.iconfinder.com/data/icons/jumpicon-basic-ui-line-1/32/-_Trash-Can--512.png" alt="Borrar">'.html_safe, unreserve_book_path(book), method: :post, remote: true, class: "ico float-right" %>
            <% elsif book.status == 2 %>
                <%= link_to '<img src="https://cdn1.iconfinder.com/data/icons/jumpicon-basic-ui-line-1/32/-_Trash-Can--512.png" alt="Borrar">'.html_safe, destroy_book_path(book), method: :delete, remote: true, class: "ico float-right", data: {confirm: "Are you sure? if you delete the book there is no money back"} %>
            <% end %>
        </div>
    </div>
</div>

app/views/books/available.html.erb
<h1>Available Books</h1>

<% if @books.any? %>
    <div id="books_list" class="row">
        <%= render @books %>
    </div>
<% else %>
    <div class="alert alert-secondary" role="alert">
        Now we don't have books available
    </div>
<% end %>

app/views/books/bought.html.erb
<h1>My Books</h1>

    <div id="books_list" class="row">
    <% if @books.any? %>
        <%= render @books %>
    <% else %>
        <div class="alert alert-secondary" role="alert">
            You haven't bougth any books
            <%= link_to "My Reserved Books to bought", books_reserved_path , class: "alert-link" %>
            or 
            <%= link_to "Available Books to reserve", books_available_path, class: "alert-link" %>
        </div>
    <% end %>
    </div>

app/views/books/destroy.js.erb
$("#books_list").html("<%= j render @books %>")

app/views/books/get_book.js.erb
$("#boton").text("")

<% if @type == 'ver' %>
    $("#modalBookLabel").text("<%= @book.title.html_safe %>")
    $("#modalBody").html("<b>Author: <%= @book.author %></b><br><p> <%= @book.review %><p>")

<% elsif @type == 'reservar' %>
    $("#modalBookLabel").text("Reservar :: <%= @book.title.html_safe %>")
    $("#modalBody").text("Estas seguro que quieres reservar <%= @book.title.html_safe %>")
    btn = '<%= link_to "Confirm reserve", reserve_book_path(@book), remote: true, method: :post,data: {disable_with: "Request processing..."}, class: "btn btn-info" %>'
    $("#boton").html(btn)

<% elsif @type == 'pagar' %>
    $("#modalBookLabel").text("Pagar :: <%= @book.title.html_safe %>")

<% end %>

$("#modalBook").modal('show')

app/views/books/pay_book.js.erb
$("#books_list").html("")

<% if @book.status == 0%>
    alert("El tiempo caduco")
<% else %>
    alert( "La compra fue exitosa! tus pagos")
<% end %>

$("#books_list").html("<%= j render @books %>")
$("#book_book_id option:selected").remove();

$("#payBookModal").modal('hide')

app/views/books/reserve_book.js.erb
$("#books_list").html("")

$("#books_list").html("<%= j render @books %>")

$("#modalBook").modal('hide')

app/views/books/reserved.html.erb
<h1>My Reserved Books</h1>

<% if @books.any? %>
    <div id="books_list" class="row">
        <%= render @books %>
    </div>
<% else %>
    <div class="alert alert-secondary" role="alert">
        You haven't reserved any books yet, go to
        <%= link_to "Available Books to reserve", books_available_path, class: "alert-link" %>
        or 
        <%= link_to "My Books", books_bought_path , class: "alert-link" %>
    </div>
<% end %>

<!-- Modal PAGO -->
<div class="modal fade" id="payBookModal" tabindex="-1" aria-labelledby="payBookLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h5 class="modal-title" id="payBookLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        </div>

        <div id="modalBody" class="modal-body">
        <%= form_tag( pay_book_path, method: "post", remote: true ) do%>
            <%= select('book', 'book_id', @books.collect {|b| [b.title, b.id]}, {:include_blank => false}, {class: 'form-control'} )%>
            <br>
            <%= submit_tag "Bought", class: "btn btn-success"%>
        <% end %>
        
        </div>
        <div class="modal-footer">
        
        </div>
    </div>
    </div>
</div>

app/views/books/unreserve_book.js.erb
$("#books_list").html("<%= j render @books %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container my-5">
      <%= yield %>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="modalBook" tabindex="-1" aria-labelledby="modalBookLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modalBookLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div id="modalBody" class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <div id="boton" >Save changes</div>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to "Library", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <%= link_to "Available Books", books_available_path, class: "nav-link" %>
                <%= link_to "My Reserved Books", books_reserved_path , class: "nav-link" %>
                <%= link_to "My Books", books_bought_path , class: "nav-link" %>
            </div>
        </div>
  </div>
</nav>